---
title: "EDLD 652 Lab 1"
author: "Chansiri, Wongphothipahan, & Loan"
date: "1/13/2021"
output: html_document
---

# Plot 1

Insert data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, 
                      include = T, 
                      warnings = F, 
                      messages = F
                      )

library(here)
library(tidyverse)
library(lubridate)
```

```{r load_data}
rstats_tweets <- readRDS(here("rstats_tweets.rds"))
```

Count screen_name and select the top 25. Arrange in descending order. Create a new data frame.

```{r}
data = rstats_tweets %>% 
   count(screen_name) %>%
   arrange(desc(n)) %>% 
   slice(seq_len(25))
```

## Plot 1 Rough Draft

Factor screen_name, create plot, coordflip.

```{r}
plot1_rough = 
  ggplot(data, aes(y = fct_reorder(screen_name,n),x = n)) + 
  geom_col() + 
  labs(y = 'screen_name') 
```

```{r echo=FALSE}
plot1_rough
```


## Plot1 Finalized

Change the axis labels, title, subtitle. Also, change fill and change background

```{r}
plot1_final = plot1_rough + 
  geom_col(fill = 'cornflowerblue') +
  labs(x  = "Count", 
       y = "Twitter Screen Name", 
       title = "Most prolific #rstats tweeters", 
       subtitle = "Top 25 screen names displayed", 
       caption = "Data from Mike Kearny, distributed via #tidutuesday") +
  theme(panel.grid.major.x = element_line(color = 'gray70'),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.background = element_rect(fill = 'white'),
        plot.caption = element_text(hjust = 0.65),
        axis.line.y = NULL)
```

```{r echo=FALSE}
plot1_final
```

# Plot 2 

```{r}
rstats_tweets_2019 <-rstats_tweets %>% 
  mutate(month = round_date(rstats_tweets$created_at, unit = 'month'),
         year = year(rstats_tweets$created_at)) %>% 
  filter(created_at < as_date("2019-01-01"))

Plotdat.2 <- 
  rstats_tweets_2019 %>% 
  count(month)
```

```{r}
Plot2_rough_draft <- 
  Plotdat.2 %>% 
  ggplot(aes(x = month, y = n)) + 
  geom_line() + 
  geom_smooth() + 
  scale_y_continuous(breaks = c(0, 4000, 8000, 12000)) + 
  xlim(as_datetime('2009-01-01'),as_datetime('2018-12-31')) 
```
```{r echo=FALSE}
suppressWarnings(print(Plot2_rough_draft))
```

```{r}
Plot2_final <- 
  Plotdat.2 %>% 
  ggplot(aes(x = month, y = n)) + 
  geom_line(color="#757575", size = 1) + 
  geom_smooth(color = "#f500e4", se = F) + 
  scale_y_continuous(breaks = c(0, 4000, 8000, 12000)) + 
  xlim(as_datetime('2009-01-01'), as_datetime('2018-12-31')) +
  geom_area(fill = "#6e91f2", alpha = .3) + 
  labs(x = "Year (data summarized by month)", y = "Number of #rstats tweets", 
       title = "Growth of the #rstats hashtag on twitter over time", 
       caption = "Data from Mike Kearny, distributed via #tidytuesday") + 
  theme_minimal()
```

```{r echo=FALSE}
suppressWarnings(print(Plot2_final))
```





